require 'rails_helper'

RSpec.describe Integrations::Jsm::CloseTicketService do
  let(:account) { create(:account) }
  let(:hook) { create(:integrations_hook, :jsm, account: account) }
  let(:conversation) do
    create(
      :conversation,
      account: account,
      status: :resolved,
      additional_attributes: {
        'jsm' => {
          'ticket_id' => '10001',
          'ticket_key' => 'SUP-123'
        }
      }
    )
  end
  let!(:incoming_message) do
    create(
      :message,
      conversation: conversation,
      account: account,
      inbox: conversation.inbox,
      message_type: 'incoming',
      content: 'Hello I cannot download the app'
    )
  end
  let!(:outgoing_message) do
    create(
      :message,
      conversation: conversation,
      account: account,
      inbox: conversation.inbox,
      message_type: 'outgoing',
      content: 'Please upgrade to Android 11.',
      sender: create(:agent_bot, :skip_validate)
    )
  end

  before do
    hook
  end

  it 'updates and resolves the linked JSM ticket through the workflow' do
    captured_request = nil
    allow(HTTParty).to receive(:post) do |url, options|
      captured_request = { url: url, options: options }
      instance_double(
        HTTParty::Response,
        success?: true,
        body: {
          data: {
            status: 'succeeded',
            outputs: {
              jira_issue_id: '10001',
              jira_issue_key: 'SUP-123'
            }
          }
        }.to_json
      )
    end

    described_class.new(conversation: conversation).perform

    expect(captured_request[:url]).to eq('https://neuai.neutron.sg/v1/workflows/run')
    expect(captured_request[:options][:headers]).to include(
      'Authorization' => "Bearer #{hook.settings['neuai_workflow_api_key']}",
      'Accept' => 'application/json',
      'Content-Type' => 'application/json'
    )

    request_body = JSON.parse(captured_request[:options][:body])
    expect(request_body).to include(
      'response_mode' => 'blocking',
      'user' => "conversation-#{conversation.id}"
    )
    expect(request_body['inputs']).to include(
      'action' => 'update_and_resolve_issue',
      'jira_issue_id' => '10001',
      'jira_cloud_id' => hook.settings['jira_cloud_id'],
      'jira_project_key' => hook.settings['jira_project_key'],
      'neuchat_channel_name' => conversation.inbox.inbox_type,
      'neuchat_conversation_id' => conversation.id
    )
    expect(request_body['inputs']['chat_history']).to include('User: Hello I cannot download the app')
    expect(request_body['inputs']['chat_history']).to include('Agent: Please upgrade to Android 11.')
    expect(request_body['inputs']['chat_history']).to include('<This response is generated by AI.>')
  end

  it 'does nothing when there is no linked JSM ticket' do
    conversation.update_column(:additional_attributes, {})
    allow(HTTParty).to receive(:post)

    described_class.new(conversation: conversation).perform

    expect(HTTParty).not_to have_received(:post)
  end

  it 'raises an error when the workflow returns an empty jira issue id' do
    allow(HTTParty).to receive(:post).and_return(
      instance_double(
        HTTParty::Response,
        success?: true,
        body: {
          data: {
            status: 'succeeded',
            outputs: {
              jira_issue_id: '',
              jira_issue_key: ''
            }
          }
        }.to_json
      )
    )

    expect do
      described_class.new(conversation: conversation).perform
    end.to raise_error(Integrations::Jsm::Client::ApiError, 'JSM workflow returned empty jira_issue_id')
  end
end
