require 'rails_helper'

RSpec.describe Integrations::Jsm::CreateTicketService do
  let(:account) { create(:account) }
  let(:hook) { create(:integrations_hook, :jsm, account: account) }
  let(:conversation) { create(:conversation, account: account) }
  let!(:incoming_message) do
    create(
      :message,
      conversation: conversation,
      account: account,
      inbox: conversation.inbox,
      message_type: 'incoming',
      content: 'Hello'
    )
  end
  let!(:attachment_message) do
    create(
      :message,
      :with_attachment,
      conversation: conversation,
      account: account,
      inbox: conversation.inbox,
      message_type: 'incoming',
      content: ''
    )
  end
  let!(:outgoing_message) do
    create(
      :message,
      conversation: conversation,
      account: account,
      inbox: conversation.inbox,
      message_type: 'outgoing',
      content: 'That should work now.',
      sender: create(:agent_bot, :skip_validate)
    )
  end

  before do
    hook
  end

  it 'creates a JSM ticket through the workflow and stores the returned ids' do
    captured_request = nil
    allow(HTTParty).to receive(:post) do |url, options|
      captured_request = { url: url, options: options }
      instance_double(
        HTTParty::Response,
        success?: true,
        body: {
          data: {
            status: 'succeeded',
            outputs: {
              jira_issue_id: '22126',
              jira_issue_key: 'SUP-456'
            }
          }
        }.to_json
      )
    end

    described_class.new(conversation: conversation).perform

    expect(captured_request[:url]).to eq('https://neuai.neutron.sg/v1/workflows/run')
    request_body = JSON.parse(captured_request[:options][:body])

    expect(request_body['inputs']).to include(
      'action' => 'create_issue',
      'jira_cloud_id' => hook.settings['jira_cloud_id'],
      'jira_project_key' => hook.settings['jira_project_key'],
      'neuchat_channel_name' => conversation.inbox.inbox_type,
      'neuchat_conversation_id' => conversation.id
    )
    expect(request_body['inputs']['chat_history']).to include('User: Hello')
    expect(request_body['inputs']['chat_history']).to include('User Image Attachment:')
    expect(request_body['inputs']['chat_history']).to include('Agent: That should work now.')
    expect(request_body['inputs']['chat_history']).to include('<This response is generated by AI.>')

    expect(conversation.reload.additional_attributes['jsm']).to eq(
      'ticket_id' => '22126',
      'ticket_key' => 'SUP-456'
    )
  end

  it 'raises an error when the workflow returns an empty jira issue id' do
    allow(HTTParty).to receive(:post).and_return(
      instance_double(
        HTTParty::Response,
        success?: true,
        body: {
          data: {
            status: 'succeeded',
            outputs: {
              jira_issue_id: '',
              jira_issue_key: ''
            }
          }
        }.to_json
      )
    )

    expect do
      described_class.new(conversation: conversation).perform
    end.to raise_error(Integrations::Jsm::Client::ApiError, 'JSM workflow returned empty jira_issue_id')
  end

  it 'does nothing when the conversation already has a linked ticket' do
    conversation.update_column(:additional_attributes, { 'jsm' => { 'ticket_id' => '22126' } })
    allow(HTTParty).to receive(:post)

    described_class.new(conversation: conversation).perform

    expect(HTTParty).not_to have_received(:post)
  end
end
