class Integrations::Jsm::ChatHistoryFormatter
  AI_GENERATED_SENDER_TYPES = %w[AgentBot Captain::Assistant].freeze

  pattr_initialize [:conversation!]

  def format
    messages = conversation.messages.where.not(message_type: :activity).where(private: false).reorder(created_at: :asc)

    messages.each_with_object([]) do |message, lines|
      append_content(lines, message)
      append_attachments(lines, message)
      append_ai_marker(lines, message)
    end.join("\n")
  end

  private

  def append_content(lines, message)
    return if message.content.blank?

    lines << "#{sender_label(message)}: #{message.content}"
  end

  def append_attachments(lines, message)
    message.attachments.each do |attachment|
      url = attachment.download_url.presence || attachment.external_url.to_s
      next if url.blank?

      lines << "#{sender_label(message)} #{attachment_label(attachment)} Attachment: #{url}"
    end
  end

  def append_ai_marker(lines, message)
    return unless AI_GENERATED_SENDER_TYPES.include?(message.sender_type)

    lines << '<This response is generated by AI.>'
  end

  def sender_label(message)
    message.incoming? ? 'User' : 'Agent'
  end

  def attachment_label(attachment)
    attachment.file_type.to_s.titleize
  end
end
