name: Auto-assign PR to Author

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull request number
        required: true

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto-assign PR to author
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = Number(context.payload.inputs.pull_number);
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            const author = pullRequest.user.login;
            
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: pull_number,
              assignees: [author]
            });
            
            console.log(`Assigned PR #${pull_number} to ${author}`);
