# ref: https://github.com/amannn/action-semantic-pull-request
# ensure PR title is in semantic format

name: "Lint PR"

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull request number
        required: true

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = Number(context.payload.inputs.pull_number);
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            const title = pullRequest.title;
            const semanticTitlePattern = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?!?: .+/;

            if (!semanticTitlePattern.test(title)) {
              core.setFailed(`PR title is not semantic: "${title}"`);
              return;
            }

            core.info(`PR title is semantic: "${title}"`);
